---
resources:
- name: ci-image
  type: registry-image
  source:
    repository: busybox
- name: automation
  type: git
  icon: github
  source:
    uri: https://github.com/emmanuelguerin/deploy-automation
    branch: ((source_branch))
- name: trigger
  type: semver
  source:
    driver:      git
    uri:         git@github.com:emmanuelguerin/pipelines-compass.git
    branch:      master
    file:        versions/((env-name))-trigger
    private_key: |
      ((github-versions-private-key))

    git_user: "Emmanuel Guerin <e.guerin@criteo.com>"
jobs:
  - name: deploy
    plan:
    - get: automation
      trigger: true
    - get: trigger
      trigger: true
    - get: ci-image
    - task: deploy
      params:
        COLOR: ((color))
        ENV_NAME: ((env-name))
        VERSION: ((component-version))
      image: ci-image
      config:
        platform: linux
        run:
          path: sh
          args:
            - "-c"
            - |
              echo "Values: $COLOR $ENV_NAME $VERSION"
              sleep 10
              echo "deploy"
