---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: gstack/gk-ops
params:
  ENV_NAME:
inputs:
  - name: automation

outputs:
  - name: prepared-pipeline

run:
  path: automation/ci/repipe/tasks/prepare-pipeline.sh

