---
resources:
# - name: ci-image
#   type: registry-image
#   source:
#     repository: busybox
- name: config
  type: git
  icon: github
  source:
    uri: https://github.com/emmanuelguerin/deploy-config
- name: automation
  type: git
  icon: github
  source:
    branch: master
    uri: https://github.com/emmanuelguerin/deploy-automation
- name: automation-staging
  type: git
  icon: github
  source:
    branch: staging
    uri: https://github.com/emmanuelguerin/deploy-automation
- name: automation-prod
  type: git
  icon: github
  source:
    branch: prod
    uri: https://github.com/emmanuelguerin/deploy-automation
jobs:
- name: repipe-sandbox
  plan:
  - get: config
    trigger: true
  - get: automation
    trigger: true
  - task: prepare-pipeline
    file: automation/ci/repipe/tasks/prepare-pipeline.yml
    params:
      ENV_NAME: sandbox
  - set_pipeline: deploy-sandbox
    file: prepared-pipeline/assembled-pipeline.yml
    var_files:
    - automation/ci/deploy-infra/config/versions.yml
    - config/sandbox/settings.yml
    vars:
      env-name: sandbox
      source_branch: master
      next_env: staging
- name: repipe-staging
  plan:
  - get: config
    trigger: true
  - get: automation-staging
    trigger: true
  - set_pipeline: deploy-staging
    file: automation-staging/ci/deploy-infra/pipeline.yml
    var_files:
    - automation-staging/ci/deploy-infra/config/versions.yml
    - config/sandbox/settings.yml
    vars:
      env-name: staging
      source_branch: staging
      next_env: prod
- name: repipe-prod
  plan:
  - get: config
    trigger: true
  - get: automation-prod
    trigger: true
  - set_pipeline: deploy-prod
    file: automation-prod/ci/deploy-infra/pipeline.yml
    var_files:
    - automation-prod/ci/deploy-infra/config/versions.yml
    - config/prod/settings.yml
    vars:
      env-name: prod
      source_branch: prod
